import streamlit as st
import yfinance as yf
import pandas as pd
import pandas_ta as ta
from datetime import datetime, timedelta

# --- Configuration ---
st.set_page_config(layout="wide", page_title="EMA Crossover & RSI Scanner")

# --- 1. Define Tickers (Direct Translation of R Code) ---

# Note: We are using a simplified, hardcoded S&P 500 list to avoid external dependency issues
# (Your original R code used 'tidyquant' to fetch the live list, which requires a more complex setup in Python)
# For the full list, you would need to implement a scraper (e.g., using 'requests' and 'BeautifulSoup')
def get_sp500_tickers_simplified():
    """Returns a simplified, partial list of S&P 500 components."""
    # A small, verifiable subset of the S&P 500
    sp500_components = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'JPM', 'JNJ', 'TSLA', 'V']
    return sp500_components

us_stocks = [
    'AAPL', 'XLV', 'NFLX', 'ALAB', 'IJR', 'AMD', 'AMZN', 'RMBS', 'VPU', 'VIS',
    'SHOP', 'SCHW', 'AVGO', 'ONDS', 'QCOM', 'META', 'NVDA', 'MRVL', 'SITM',
    'ISRG', 'BRK-B', 'CRWD', 'TSLA', 'ASML', 'NBIS', 'PLTR', 'GOOGL', 'HIMS',
    'VRT', 'NRG', 'RTX', 'NVTS', 'CRUS', 'ENPH', 'PYPL', 'SOFI', 'MU', 'VST',
    'AOSL', 'CRDO', 'TEM', 'ZS', 'LLY', 'TTEK', 'MORN', 'SPXC', 'GTLS', 'PPC',
    'CPAY', 'CAG', 'TAP', 'DVA', 'AA', 'BTC-USD'
]

tw_top_50_raw = [
    '2330', '2317', '2454', '2308', '2382', '2891', '3711', '2881', '2882',
    '2886', '2303', '2357', '2884', '2892', '3231', '2885', '2379', '6669',
    '2345', '2890', '2887', '5871', '2327', '2883', '3034', '1216', '1303',
    '2412', '3045', '3008', '2383', '4938', '3661', '2002', '1301', '2207',
    '5880', '2912', '2603', '4904', '2395', '1326', '2301', '3017', '2609',
    '2615', '1101', '5876', '6505', '9910'
]

tw_mid_100_raw = [
    '2360', '3665', '2449', '3037', '2344', '3653', '2408', '2385', '2376',
    '1590', '2801', '1319', '2313', '1476', '3036', '3533', '1513', '1605',
    '2409', '3481', '2353', '2356', '2324', '1102', '1229', '2834', '1402',
    '2880', '2812', '2377', '2855', '9904', '2618', '2474', '2347', '8046',
    '6239', '1722', '2371', '2633', '1477', '4958', '2404', '6415', '6770',
    '3702', '1504', '8464', '3706', '3044', '6176', '1210', '2027', '2354',
    '6285', '3023', '2105', '8454', '2402', '6269', '1802', '2374', '2606',
    '2201', '1795', '2610', '5879', '2542', '2206', '4763', '5434',
    '1723', '9921', '6139', '6531', '3443', '2368', '2458', '6446', '6191',
    '2049', '1519', '1717', '3592', '8016', '3708', '4915', '2492', '9938',
    '2337', '2340', '5347', '2059', '3406', '6719', '1589', '2417', '1312'
]

# Append ".TW" and remove duplicates
tw_stocks_raw = list(set(tw_top_50_raw + tw_mid_100_raw))
tw_tickers = [f"{t}.TW" for t in tw_stocks_raw]

# Additional TW ETF
tw_etf = ["00631L.TW"]

# --- 2. Main Scan Logic Function ---

@st.cache_data(ttl=timedelta(hours=4))
def run_scan(all_tickers):
    """Fetches data, calculates indicators, and runs the signal logic for all tickers."""
    buy_signals = []
    sell_signals = []
    failed_tickers = []
    
    # Use today's date and a lookback period (e.g., 100 days)
    end_date = datetime.now()
    start_date = end_date - timedelta(days=100)

    # Use a progress bar for user feedback
    progress_bar = st.progress(0, text="Starting scan...")
    total_tickers = len(all_tickers)

    for i, ticker in enumerate(all_tickers):
        progress = (i + 1) / total_tickers
        progress_bar.progress(progress, text=f"Scanning {ticker} ({i+1}/{total_tickers})...")

        try:
            # --- Data Fetching (yfinance) ---
            data = yf.download(ticker, start=start_date, end=end_date, progress=False)

            if data.empty or len(data) < 30:
                failed_tickers.append(ticker)
                continue
            
            # --- Indicator Calculation (pandas_ta) ---
            # Calculate EMA(13), EMA(26), and RSI(14) - standard RSI period is 14
            data.ta.ema(length=13, append=True)
            data.ta.ema(length=26, append=True)
            data.ta.rsi(length=14, append=True)

            # Column names generated by pandas_ta
            EMA_13_COL = 'EMA_13'
            EMA_26_COL = 'EMA_26'
            RSI_COL = 'RSI_14'
            
            # Drop rows with NaN values created by indicator lookback periods
            data.dropna(inplace=True)

            if len(data) < 2:
                # Not enough data for indicator comparison
                failed_tickers.append(ticker)
                continue

            # --- Signal Logic ---
            # Get the latest two rows (Yesterday and Today)
            today = data.iloc[-1]
            yesterday = data.iloc[-2]

            ema_13_yest = yesterday[EMA_13_COL]
            ema_26_yest = yesterday[EMA_26_COL]
            ema_13_today = today[EMA_13_COL]
            ema_26_today = today[EMA_26_COL]
            last_rsi_value = today[RSI_COL]
            last_close = today['Close']

            # EMA Crossover Logic
            ema_cross_up = (ema_13_yest < ema_26_yest) and (ema_13_today > ema_26_today)
            ema_cross_down = (ema_13_yest > ema_26_yest) and (ema_13_today < ema_26_today)

            # RSI Filter Logic
            rsi_is_bullish = (last_rsi_value > 50)
            rsi_is_bearish = (last_rsi_value < 50)

            signal_data = {
                'Ticker': ticker,
                'Close': f"{last_close:.2f}",
                'EMA_13': f"{ema_13_today:.2f}",
                'EMA_26': f"{ema_26_today:.2f}",
                'RSI': f"{last_rsi_value:.2f}"
            }

            if ema_cross_up and rsi_is_bullish:
                buy_signals.append(signal_data)
                
            if ema_cross_down and rsi_is_bearish:
                sell_signals.append(signal_data)

        except Exception as e:
            # Catch errors like 'Cannot read properties of None' (no data)
            failed_tickers.append(ticker)
            # st.error(f"Error processing {ticker}: {e}") # Optional: for debugging

    progress_bar.empty()
    return pd.DataFrame(buy_signals), pd.DataFrame(sell_signals), failed_tickers

# --- 3. Streamlit UI Function ---

def main():
    st.title("📈 Stock Signal Check App (EMA + RSI Filter)")
    st.markdown("---")

    # --- Sidebar for Ticker Selection ---
    with st.sidebar:
        st.header("⚙️ Scanner Settings")
        
        # Define Ticker Grouping for the UI
        ticker_groups = {
            "S&P 500 (Sample)": get_sp500_tickers_simplified(),
            "Custom US Stocks": us_stocks,
            "TW Stocks (Top 150)": tw_tickers,
            "TW ETF (00631L.TW)": tw_etf
        }
        
        selected_keys = st.multiselect(
            "Select Ticker Lists to Scan:",
            options=list(ticker_groups.keys()),
            default=["Custom US Stocks", "TW Stocks (Top 150)"]
        )

        # Combine selected lists into a single unique list
        selected_tickers = []
        for key in selected_keys:
            selected_tickers.extend(ticker_groups[key])
            
        all_tickers = sorted(list(set(selected_tickers)))

        st.info(f"Scanning **{len(all_tickers)}** unique tickers.")
        st.caption("Data is cached for 4 hours to speed up subsequent runs.")
        
        run_button = st.button("▶️ Run Technical Scan")
        
    st.header(f"Results for Scan on: {datetime.now().strftime('%Y-%m-%d')}")
    st.caption(f"Analysis uses: **EMA(13/26) Crossover** + **RSI(14) > 50 (Bullish) / < 50 (Bearish)**")
    
    # --- Execute Scan ---
    if run_button and all_tickers:
        buy_df, sell_df, failed_tickers = run_scan(all_tickers)
        
        st.markdown("---")

        # Display Buy Signals
        st.subheader(f"🟢 Bullish Crossovers (Buy Signals) - {len(buy_df)}")
        if not buy_df.empty:
            st.dataframe(buy_df, use_container_width=True, hide_index=True)
        else:
            st.info("No bullish crossover signals found based on the filters.")

        st.markdown("---")

        # Display Sell Signals
        st.subheader(f"🔴 Bearish Crossovers (Sell Signals) - {len(sell_df)}")
        if not sell_df.empty:
            st.dataframe(sell_df, use_container_width=True, hide_index=True)
        else:
            st.info("No bearish crossover signals found based on the filters.")

        st.markdown("---")

        # Display Failed Tickers
        st.subheader(f"⚠️ Failed Tickers - {len(failed_tickers)}")
        if failed_tickers:
            st.warning(f"Could not retrieve data for **{len(failed_tickers)}** tickers. They may be delisted or have temporary data issues.")
            st.dataframe(pd.DataFrame({'Ticker': failed_tickers}), use_container_width=False, hide_index=True)
        else:
            st.success("All selected tickers were successfully scanned.")
    elif run_button and not all_tickers:
         st.error("Please select at least one list of tickers to scan in the sidebar.")

    # Show a prompt to run the scan initially
    if not run_button and not all_tickers:
         st.info("Select the lists you want to scan in the sidebar and click 'Run Technical Scan' to begin.")
         
# --- Run the Streamlit App ---
if __name__ == '__main__':
    main()
